apiVersion: v1
kind: Service
metadata:
  name: bookkeeper-service
  namespace: sdata

spec:
  selector:
    app: bookkeeper

  ports:

    - name: bookie
      port: 3181
      targetPort: 3181

  type: ClusterIP