apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: sdata

spec:
  replicas: 1

  selector:
    matchLabels:
      app: zookeeper

  template:
    metadata:
      labels:
        app: zookeeper

    spec:
      containers:
        - name: zookeeper

          image: apachepulsar/pulsar:4.0.6

          imagePullPolicy: IfNotPresent

          command:
            - bin/pulsar

          args:
            - zookeeper

          ports:
            - containerPort: 2181

          env:
            - name: PULSAR_MEM
              value: "-Xms256m -Xmx256m"

          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 20