apiVersion: v1
kind: Service

metadata:
  name: dragonfly-service
  namespace: sdata
  labels:
    app: dragonfly

spec:
  type: ClusterIP

  selector:
    app: dragonfly

  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP