fullnameOverride: kong

deployment:

  kong:
    enabled: true

env:

  database: "off"

proxy:

  enabled: true

  type: LoadBalancer

  http:
    enabled: true

  tls:
    enabled: false

admin:

  enabled: true

  type: ClusterIP

manager:

  enabled: true

  type: ClusterIP

ingressController:

  enabled: true

enterprise:

  enabled: false

resources:

  requests:

    cpu: 200m

    memory: 256Mi

  limits:

    cpu: "1"

    memory: 1Gi